export * from './CreateUserBody';
export * from './LoginBody';
export * from './RegisterResponse';
export * from './IParking';
export * from './IBook';
export * from './ICar';
export * from './IPlace';
export * from './IUser';
export * from './IRoute';
